# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{fight_csv}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Manuel Korfmann"]
  s.date = %q{2011-06-11}
  s.description = %q{
Provides a nice DSL to describe your CSV document.
CSV documents can be validated against this description.
You can easily define types like Integer or Array for CSV through converters.
}
  s.email = %q{manu@korfmann.info}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/fight_csv.rb",
    "lib/fight_csv/data_source.rb",
    "lib/fight_csv/field.rb",
    "lib/fight_csv/parser.rb",
    "lib/fight_csv/record.rb",
    "lib/fight_csv/schema.rb",
    "sketch.rb",
    "test/fixtures/cocktails.csv",
    "test/fixtures/prog_lang_schema.rb",
    "test/fixtures/programming_languages.csv",
    "test/fixtures/recipes.csv",
    "test/helper.rb",
    "test/test_field.rb",
    "test/test_fight_csv.rb",
    "test/test_parser.rb",
    "test/test_record.rb",
    "test/test_schema.rb"
  ]
  s.homepage = %q{http://github.com/mkorfmann/fight_csv}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{JSON-Schema + ActiveModel for CSV}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<constructable>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_development_dependency(%q<awesome_print>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
    else
      s.add_dependency(%q<constructable>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_dependency(%q<awesome_print>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
    end
  else
    s.add_dependency(%q<constructable>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
    s.add_dependency(%q<awesome_print>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
  end
end

